### ISSUE TITLE
Recommended pattern to retrieve the bio of a given ORCID

### ISSUE THREAD

**Issue by kaplun** [ORCID/python-orcid#10]
With the members API, using this package, what is the recommended pattern to e.g. retrieve the bio of a given ORCID profile (i.e. not search for the profile, but given an ORCID ID directly retrieve information).

**Comment by kaplun** [comment]
@MSusik since you are still keeping an eye on this project, do you know the answer?

**Comment by MSusik** [comment]
@kaplun When I implemented the newest version, if I remember correctly, there was no method of checking the full biography part with API 2.0_rc2. Obviously if it is available now, it should be implemented.

@rcpeters how does the situation with 2.0_rc2 and orcid-bio look today? Is it possible to download a user's bio?

**Comment by rcpeters** [comment]
It's not officially released as we are still cleaning up some backend data
issues with writing. For reading you should be fine:

https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_2.0_rc2/README.md

Sample Curl:

curl -i -H "Accept: application/orcid+xml" -H 'Authorization: Bearer
REPLACE_WITH_TOKEN' '
https://api.sandbox.orcid.org/v2.0_rc2/0000-0002-1306-4180/personal-details'

Cheers,
Rob

On Wed, Jun 15, 2016 at 1:52 PM, Mateusz Susik notifications@github.com
wrote:

> @kaplun https://github.com/kaplun When I implemented the newest
> version, if I remember correctly, there was no method of checking the full
> biography part with API 2.0_rc2. Obviously if it is available now, it
> should be implemented.
> 
> @rcpeters https://github.com/rcpeters how does the situation with
> 2.0_rc2 and orcid-bio look today?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ORCID/python-orcid/issues/10#issuecomment-226316339,
> or mute the thread
> https://github.com/notifications/unsubscribe/AALx5El7h6Ik55WvetvsTX0vS4wLSCo1ks5qMGYHgaJpZM4I1tGO
> .

## 

Robert Peters
info@rcpeters.com
805.440.9056

**Comment by MSusik** [comment]
@rcpeters  Thanks a lot! 
@kaplun It seems that the biography support doesn't require large changes in the code, so I will probably implement it soon.

**Comment by MSusik** [comment]
@kaplun I just added few lines to integrate all of the reading API. See c3240dafab38cb11f6bcc0ee076e7dee5bbebf56 and the link from Robert for details! The new release is 0.7.0 and it's available on PyPI

The add/update code should be updated as well, feel free to contribute.

**Comment by kaplun** [comment]
@MSusik thanks! 

Next time would be nice if you can send a PR before, just to give the time to review, and double check it will not impact production installations (I am sure you did a great job here, but it's really to be sure).

**Comment by MSusik** [comment]
@kaplun 

> just to give the time to review, and double check it will not impact production installations 

Can I assume that you are willing to review and double check next PRs? I didn't create the previous one, as I thought I am the only main contributor.

Obviously, the back compability will be preserved whenever possible (like in this case).
