### ISSUE TITLE
How could I get pass institution's key and secret? 

### ISSUE THREAD

**Issue by avatar-lavventura** [ORCID/python-orcid#25]
My university does not exist under institutional account (Bogazici University). But I do have a personal account.

**[Q]** How could I get pass institution's key and secret?  Can I get via my personal account?

**Comment by MSusik** [comment]
Unfortunately I don't know, but @rcpeters should be able to help you.

**Comment by avatar-lavventura** [comment]
Some how I was able to get my client key and secret and obtain my token key under `Developer Tools` (https://orcid.org/developer-tools).

But I do have this error: `error="invalid_token", error_description="Invalid access token: '...'`  (https://github.com/ORCID/ORCID-Source/issues/4565), when I am using public API through `curl`. I am not sure what might be the reason. @MSusik

**Comment by rcpeters** [comment]
You institution would need to have ORCID membership(
https://orcid.org/about/membership) and they would have to list you as a
technical contact. As for the invalid token error message please see your
other thread: https://github.com/ORCID/ORCID-Source/issues/4565.

Robert Peters
info@rcpeters.com
415.374.0214
805.440.9056

**Comment by MSusik** [comment]
Thanks for clarification @rcpeters!
